development:
  adapter: postgresql
  database: testapp_development
  encoding: utf8

test:
  adapter: postgresql
  database: testapp_test
  encoding: utf8

production:
  adapter: postgresql
  database: testapp_production
  encoding: utf8
