default: &default
  adapter: postgresql
  encoding: utf8

development:
  << *default
  database: testapp_development

test:
  << *default
  database: testapp_test

production:
  << *default
  database: testapp_production
